import { AlertTriangle, Coins, House, Info, RefreshCw, Sparkles, Zap } from 'lucide-react'
import type { Meal } from '../../lib/types'
import { Button } from '../ui/Button'
import { Card, CardHeader } from '../ui/Card'

const sum = (meals: Meal[], key: 'calories' | 'protein' | 'fat' | 'carbs' | 'fiber') => Math.round(meals.reduce((total, meal) => total + meal[key], 0) * 10) / 10

export function MealPlan({ meals, onMode, warnings = [], pantryActive = false, targetCalories }: { meals: Meal[]; onMode: (mode: string) => void; warnings?: string[]; pantryActive?: boolean; targetCalories?: number }) {
  const totals = { calories: sum(meals, 'calories'), protein: sum(meals, 'protein'), fat: sum(meals, 'fat'), carbs: sum(meals, 'carbs'), fiber: sum(meals, 'fiber') }
  return <Card>
    <CardHeader eyebrow={pantryActive ? '4 прийоми · з домашнього списку' : '4 прийоми'} title="Раціон на день" action={<Button variant="ghost" onClick={() => onMode('regenerate')} className="h-8 px-2.5"><RefreshCw size={14}/>Інший</Button>}/>
    <div className="p-4 sm:p-5">
      {warnings.length > 0 && <div className="mb-4 rounded-2xl border border-amber-300/15 bg-amber-300/[.05] p-3.5"><p className="flex items-center gap-2 text-xs font-semibold text-amber-200"><AlertTriangle size={15}/>Перевір план</p><ul className="mt-2 space-y-1.5 text-xs leading-relaxed text-amber-100/65">{warnings.map(warning => <li key={warning}>· {warning}</li>)}</ul></div>}
      <div className="mb-4 flex flex-wrap gap-2"><Button variant="secondary" className="h-8 px-3 text-xs" onClick={() => onMode('cheap')}><Coins size={14}/>Дешевше</Button><Button variant="secondary" className="h-8 px-3 text-xs" onClick={() => onMode('simple')}><Zap size={14}/>Простіше</Button><Button variant="secondary" className="h-8 px-3 text-xs" onClick={() => onMode('protein')}><Sparkles size={14}/>Більше білка</Button></div>

      <div className="mb-4 rounded-2xl border border-lime/10 bg-lime/[.035] p-4"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-[10px] font-bold uppercase tracking-[.14em] text-lime">Фактично за день</p><p className="mt-1 text-xl font-bold text-white">{totals.calories} <span className="text-xs font-normal text-zinc-500">ккал</span></p></div>{targetCalories && <p className="text-[11px] text-zinc-500">Ціль: {targetCalories} ккал · різниця {totals.calories - targetCalories > 0 ? '+' : ''}{Math.round(totals.calories - targetCalories)}</p>}</div><div className="mt-3 flex flex-wrap gap-x-4 gap-y-1 text-xs"><span className="text-rose-300">Б {totals.protein} г</span><span className="text-amber-300">Ж {totals.fat} г</span><span className="text-sky-300">В {totals.carbs} г</span><span className="text-emerald-300">Клітковина {totals.fiber} г</span></div></div>

      <div className="grid gap-3 lg:grid-cols-2">{meals.map((meal, index) => <article key={`${meal.name}-${index}`} className="rounded-2xl border border-white/[.07] bg-white/[.025] p-4"><div className="flex items-start justify-between gap-3"><div><span className="text-[10px] font-bold uppercase tracking-[.14em] text-lime">{String(index+1).padStart(2,'0')} · {meal.label}</span><h3 className="mt-1 text-sm font-semibold text-white">{meal.name}</h3></div><b className="whitespace-nowrap text-sm text-white">{meal.calories} <span className="text-[10px] font-normal text-zinc-500">ккал</span></b></div><ul className="mt-3 space-y-1.5 text-xs text-zinc-400">{meal.foods.map(food => { const fromHome = meal.homeFoods?.includes(food); return <li key={food} className="flex items-center justify-between gap-2"><span>· {food}</span>{fromHome && <span className="inline-flex shrink-0 items-center gap-1 rounded-md bg-lime/[.08] px-1.5 py-0.5 text-[9px] font-semibold text-lime"><House size={10}/>вдома</span>}</li> })}</ul><div className="mt-3 flex flex-wrap gap-3 border-t border-white/[.06] pt-3 text-[11px]"><span className="text-rose-300">Б {meal.protein} г</span><span className="text-amber-300">Ж {meal.fat} г</span><span className="text-sky-300">В {meal.carbs} г</span><span className="text-emerald-300">Кл {meal.fiber} г</span></div><p className="mt-2 text-[11px] leading-relaxed text-zinc-600">{meal.note}</p></article>)}</div>
      <p className="mt-4 flex gap-2 rounded-xl bg-white/[.025] p-3 text-[11px] leading-relaxed text-zinc-500"><Info size={14} className="mt-0.5 shrink-0 text-zinc-400"/>Розрахунки приблизні. Реальні значення залежать від бренду, способу приготування і ваги продукту до/після приготування. Дані продукту зберігаються централізовано, тому брендове БЖУ можна буде редагувати в одному місці.</p>
    </div>
  </Card>
}
