import { ArrowRight, CheckCircle2, Droplets, Flame, Footprints, PackageCheck, Target } from 'lucide-react'
import type { NutritionPlan, Page, Profile, ProgressLog as Log, QualityCriteria } from '../lib/types'
import { goalLabels } from '../lib/constants'
import { qualityScore } from '../lib/foodQuality'
import { generateTraining } from '../lib/training'
import { Card, CardHeader } from '../components/ui/Card'
import { Badge } from '../components/ui/Badge'

export function DashboardPage({ profile, plan, quality, logs, proteinServings, onNavigate }: { profile: Profile; plan: NutritionPlan; quality: QualityCriteria; logs: Log[]; proteinServings: number; onNavigate: (p: Page) => void }) {
 const score = qualityScore(quality), workout = generateTraining(profile)[0], last = logs[0]
 return <div className="space-y-5"><section className="rounded-3xl border border-white/[.08] bg-[#141715] p-5 sm:p-7"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><Badge tone="good">{goalLabels[profile.goal]}</Badge><h2 className="mt-4 text-2xl font-bold tracking-tight text-white sm:text-3xl">Привіт, {profile.name}. <span className="text-zinc-500">План зібрано.</span></h2><p className="mt-2 max-w-xl text-sm text-zinc-500">Не потрібно робити ідеально. Сьогодні достатньо влучити в орієнтири та виконати наступний крок.</p></div><button onClick={() => onNavigate('profile')} className="flex items-center gap-2 text-xs font-semibold text-zinc-400 hover:text-white">Оновити дані <ArrowRight size={14}/></button></div></section>
 <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[
  ['Калорії', `${plan.calories}`, 'ккал / день', Flame, 'text-lime'], ['Вага', `${profile.weight}`, 'кг зараз', Target, 'text-sky-300'], ['Вода', `${plan.water}`, 'літра / день', Droplets, 'text-sky-300'], ['Кроки', profile.steps.toLocaleString('uk-UA'), 'у середньому', Footprints, 'text-amber-300']
 ].map(([label,value,sub,Icon,color]) => <Card key={label as string} className="p-4"><div className="flex items-start justify-between"><p className="text-xs text-zinc-500">{label as string}</p><Icon size={17} className={color as string}/></div><p className="mt-3 text-2xl font-bold text-white">{value as string}</p><p className="mt-1 text-[11px] text-zinc-600">{sub as string}</p></Card>)}</div>
 <div className="grid gap-5 xl:grid-cols-[1.15fr_.85fr]"><Card><CardHeader eyebrow="Харчування" title="Орієнтири на день" action={<button className="text-xs text-zinc-500 hover:text-white" onClick={() => onNavigate('nutrition')}>Відкрити</button>}/><div className="p-5"><div className="grid grid-cols-3 gap-3">{[['Білки',plan.protein,'text-rose-300'],['Жири',plan.fat,'text-amber-300'],['Вуглеводи',plan.carbs,'text-sky-300']].map(([label,value,color]) => <div key={label as string} className="rounded-xl bg-white/[.035] p-3"><p className="text-[11px] text-zinc-500">{label as string}</p><p className={`mt-1 text-lg font-bold ${color}`}>{value as number}<span className="ml-1 text-[10px] font-normal text-zinc-600">г</span></p></div>)}</div><div className="mt-3 flex items-center gap-3 rounded-xl bg-white/[.035] p-3"><PackageCheck size={18} className={profile.proteinSupplement.enabled ? 'text-lime' : 'text-zinc-600'}/><div><p className="text-xs font-semibold text-white">Протеїн: {profile.proteinSupplement.enabled ? 'використовується ✅' : 'не використовується'}</p>{profile.proteinSupplement.enabled && <p className="mt-1 text-[11px] text-zinc-500">{proteinServings ? `${proteinServings} ${proteinServings === 1 ? 'порція' : 'порції'} сьогодні` : 'Сьогодні не потрібен — білка з їжі достатньо'}</p>}</div></div><button onClick={() => onNavigate('nutrition')} className="mt-4 flex w-full items-center gap-3 rounded-xl border border-white/[.07] p-3 text-left"><div className="relative grid size-11 shrink-0 place-items-center rounded-full bg-lime/10 text-sm font-bold text-lime">{score}</div><div><p className="text-xs font-semibold text-white">Якість раціону · {score}/100</p><p className="mt-1 text-[11px] text-zinc-500">{score >= 85 ? 'Сильна база. Тримай різноманіття.' : 'Переглянь маркери й підтягни слабкі місця.'}</p></div><ArrowRight size={14} className="ml-auto text-zinc-600"/></button></div></Card>
 <Card><CardHeader eyebrow="Наступне тренування" title={workout.title} action={<Badge>{workout.focus}</Badge>}/><div className="p-5"><div className="space-y-3">{workout.exercises.slice(0,4).map((ex,i) => <div key={ex.name} className="flex items-center gap-3 text-xs"><span className="grid size-7 place-items-center rounded-lg bg-white/[.05] text-[10px] text-zinc-500">{i+1}</span><span className="flex-1 text-zinc-300">{ex.name}</span><b className="text-zinc-500">{ex.sets}×{ex.reps}</b></div>)}</div><button onClick={() => onNavigate('training')} className="mt-4 flex items-center gap-2 text-xs font-semibold text-lime">Вся програма <ArrowRight size={14}/></button></div></Card></div>
 <Card><CardHeader eyebrow="Останній check-in" title={last ? `${last.weight} кг · ${new Date(last.date+'T12:00:00').toLocaleDateString('uk-UA')}` : 'Даних ще немає'} action={last && <CheckCircle2 size={18} className="text-lime"/>}/><div className="flex flex-col gap-3 p-5 text-xs text-zinc-400 sm:flex-row sm:items-center sm:justify-between"><p>{last ? `Сон ${last.sleep} год · Енергія ${last.energy}/5 · Голод ${last.hunger}/5` : 'Зроби перший запис, щоб бачити динаміку й отримувати корекції.'}</p><button onClick={() => onNavigate('progress')} className="flex items-center gap-2 font-semibold text-white">До прогресу <ArrowRight size={14}/></button></div></Card></div>
}
